### PR TITLE
Adding LiveStream-kt Library

### PR DESCRIPTION
**Pull request by PatilShreyas**
Hi, I've developed a new kotlin library - [***`LiveStream-kt`***](https://github.com/PatilShreyas/LiveStream-kt). LiveStream is a simple class which makes communication easy among different modules of your application.
Please add it to the list.

### CODE REVIEW

**Comment by gyulavoros** [comment]
Can you please double-check the Maven coordinates?

```
http -v "http://dl.bintray.com/patilshreyas/maven/dev.shreyaspatil/LiveStream-kt/maven-metadata.xml"
GET /patilshreyas/maven/dev.shreyaspatil/LiveStream-kt/maven-metadata.xml HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Host: dl.bintray.com
User-Agent: HTTPie/2.0.0

HTTP/1.1 404 Not Found
Connection: keep-alive
Content-Encoding: gzip
Content-Type: text/plain
Date: Thu, 27 Feb 2020 14:34:14 GMT
Server: nginx
Transfer-Encoding: chunked

The requested path was not found.
```

**Comment by PatilShreyas** [comment]
@gyulavoros Thanks for letting me know about it. I've fixed this link/maven coordinates.

**Comment by gyulavoros** [comment]
One last remark, I didn't notice for the first time, can you please use `https` for `mavenMetaUrl `?

**Comment by PatilShreyas** [comment]
@gyulavoros I've changed it to `https`. Thanks for this and sorry for such mistakes.

**Pull request merged**
