### PR TITLE
Add ExpediaDotCom-graphql-kotlin

### PR DESCRIPTION
**Pull request by smyrick**
https://github.com/ExpediaDotCom/graphql-kotlin

We are already in `awesome-kotlin` https://kotlin.link/?q=graphql-kotlin

### CODE REVIEW

**Comment by smyrick** [comment]
I have a PR out to change the group id so I will need to update that before or after the merge: https://github.com/ExpediaDotCom/graphql-kotlin/pull/105

**Comment by smyrick** [comment]
Updated, good to go

**Comment by smyrick** [comment]
I am closing so I don't have open PRs but this is still valid if this can be merged

**Comment by gyulavoros** [comment]
@smyrick Sorry for the delay, your lib looks great, can you please reopen the PR?

**Pull request closed without merging**
